{{- if .Values.collector.enabled }}
# collector_cluster_role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "wavefront-operator.collector.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "wavefront-operator.collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "wavefront-operator.collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
