{{- if .Values.collector.enabled }}
apiVersion: wavefront.com/v1alpha1
kind: WavefrontCollector
metadata:
  name: {{ template "wavefront-operator.collector.fullname" . }}
spec:
  image: {{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}
  daemon: {{ .Values.collector.useDaemonset }}
  configName: {{ template "wavefront-operator.collector.fullname" . }}-config

  env:
  - name: HOST_PROC
    value: /host/proc
  - name: POD_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName
  - name: POD_NAMESPACE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

  tolerations:
  - effect: NoSchedule
    key: node.alpha.kubernetes.io/role
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

  {{- if .Values.collector.enableAutoUpgrade }}
  enableAutoUpgrade: {{ .Values.collector.enableAutoUpgrade }}
  {{- end -}}
{{- end }}
