{{- if .Values.operator.enabled }}
# operator_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wavefront-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "wavefront-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "wavefront-operator.fullname" . }}
    spec:
      serviceAccountName: {{ template "wavefront-operator.fullname" . }}
      containers:
        - name: wavefront-operator
          # Replace this with the built image name
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
          command:
          - wavefront-operator
          imagePullPolicy: {{ .Values.operator.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wavefront-operator"
{{- end }}