{{- if .Values.operator.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "wavefront-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "wavefront-operator.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "wavefront-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}