{{- if .Values.proxy.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: wavefrontproxies.wavefront.com
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: wavefront.com
  names:
    kind: WavefrontProxy
    listKind: WavefrontProxyList
    plural: wavefrontproxies
    singular: wavefrontproxy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                advanced:
                  type: object
                dataPreprocess:
                  properties:
                    blacklistRegex:
                      type: string
                    customSourceTags:
                      type: string
                    prefix:
                      type: string
                    preprocessorConfigFile:
                      type: object
                    whitelistRegex:
                      type: string
                  type: object
                histogram:
                  properties:
                    histogramDistPorts:
                      description: Comma-separated list of ports to listen on for
                        Wavefront histogram distribution formatted data. This is usually
                        40000
                      type: string
                  type: object
                metrics:
                  type: object
                trace:
                  properties:
                    jaegerPorts:
                      description: Comma-separated list of ports on which to listen
                        on for Jaeger Thrift formatted data. Defaults to none. This
                        is usually 30001
                      format: int32
                      type: integer
                    tracePorts:
                      description: Comma-separated list of ports to listen on for
                        Wavefront trace formatted data. Defaults to none. This is
                        usually 30000
                      format: int32
                      type: integer
                    traceSamplingDuration:
                      description: When this is set to a value greater than 0, spans
                        that are greater than or equal to this value will be sampled.
                      format: float
                      type: number
                    traceSamplingRate:
                      description: Sampling rate to apply to tracing spans sent to
                        the proxy. This rate is applied to all data formats the proxy
                        is listening on. Value should be between 0.0 and 1.0.  Default
                        is 1.0
                      format: float
                      type: number
                    zipkinPorts:
                      description: Comma-separated list of ports on which to listen
                        on for Zipkin Thrift formatted data. Defaults to none. This
                        is usually 9411
                      format: int32
                      type: integer
                  type: object
              type: object
            image:
              description: The WavefrontProxy image to use. Defaults to wavefronthq/proxy:latest
              type: string
            metricPorts:
              description: // The port number the proxy will listen on for metrics
                in Wavefront data format. // This is usually port 2878
              format: int32
              type: integer
            proxyEnabled:
              description: Whether proxy is enabled.
              type: boolean
            size:
              description: The no. of replicas for Wavefront Proxy
              format: int32
              type: integer
            token:
              description: Wavefront API Token.
              type: string
            url:
              description: Wavefront URL (cluster).
              type: string
          type: object
        status:
          properties:
            createdTimestamp:
              format: date-time
              type: string
            updatedTimestamp:
              format: date-time
              type: string
            version:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
{{- end }}
