# wavefrontproxy_cr.yaml
apiVersion: wavefront.com/v1alpha1
kind: WavefrontProxy
metadata:
  name: example-wavefrontproxy
  namespace: wavefront
spec:
  image: wavefronthq/proxy:latest
  url: https://nimba.wavefront.com/api/
  token: 875c0e35-edb1-46a1-8a9e-a9d76ab3739b
  size: 1
  proxyEnabled: true
  metricPorts: 2878

---

# wavefrontproxy_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  namespace: wavefront
  labels:
   k8s-app: wavefront-proxy
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  selector:
    app: wavefront-proxy
