apiVersion: wavefront.com/v1alpha1
kind: WavefrontProxy
metadata:
  name: example-wavefrontproxy
  namespace: wavefront-collector
spec:
  image: wavefronthq/proxy:latest
  url: https://nimba.wavefront.com/api/
  token: 875c0e35-edb1-46a1-8a9e-a9d76ab3739b
  size: 3
  proxyEnabled: true
  metricPorts: 2878
  proxyConfig:
    metrics:
    trace:
    histogram:
    dataPreprocess:
    advanced:
