## wavefront_proxy advanced configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-config
  namespace: wavefront
data:
  wavefront.conf: |
    prefix = dev
    traceListenerPorts=30000
    customSourceTags = <YOUR_K8S_CLUSTER>

---
## wavefront_proxy preprocessor configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: preprocessor-config
  namespace: wavefront
data:
  rules.yaml: |
    '2878':
      - rule    : add-cluster-tag
        action  : addTag
        tag     : env
        value   : dev
#      - rule    : drop-generated-label-tags
#        action  : dropTag
#        tag     : label\.(controller-revision-hash|pod-template-.*|.*kubernetes\.io.*)

---
# wavefrontproxy_cr.yaml
apiVersion: wavefront.com/v1alpha1
kind: WavefrontProxy
metadata:
  name: example-wavefrontproxy
  namespace: wavefront
spec:
  url: <https://YOUR_CLUSTER.wavefront.com/api/>
  token: <TOKEN>
  preprocessor: preprocessor-config
  advanced: advanced-config
  additionalPorts: "30000"
