kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wavefront-operator
  namespace: wavefront-collector
subjects:
- kind: ServiceAccount
  name: wavefront-operator
roleRef:
  kind: Role
  name: wavefront-operator
  apiGroup: rbac.authorization.k8s.io
